Change matplotlib as an optional dependency (#2029)
This PR proposes to change matplotlib as an optional dependency.

```python
>>> from databricks import koalas as ks
>>> ks.range(100).plot.bar()
Traceback (most recent call last):
  ...
ImportError: matplotlib is required for plotting when the default backend 'matplotlib' is selected.
```

Resolves #issues