Test requirement-dev.txt against pip as well in CI (#395)
This PR proposes to test `pip` at Python 3.5. We provide a `requirement-dev.txt` file that can be used at both `pip` and `conda`.

This is because:

**1. We should test `pip` compatibility of `requirement-dev.txt` file:**

We met the compatibility issue before at https://github.com/databricks/koalas/pull/154. We can prevent this via running it in Travis CI.


**2. One of the dependency in Koalas, `mlflow` requires Python 3.6 specifically in Conda:**


mlflow requires Python 3.6+ if we use conda

```
conda install -c conda-forge --yes mlflow
Collecting package metadata: done
Solving environment: failed

SpecsConfigurationConflictError: Requested specs conflict with configured specs.
  requested specs:
    - mlflow
  pinned specs:
    - python=3.5
Use 'conda config --show-sources' to look for 'pinned_specs' and 'track_features'
configuration parameters.  Pinned specs may also be defined in the file
```

although mlflow doesn't specify the Python versions to force.

One or one of the culprits seems to be `docker-py` - it seems requiring Python 3.6+ for docker-py 3.6.0+. However, mlflow specifies it 3.6.0+ (https://github.com/conda-forge/mlflow-feedstock/blob/master/recipe/meta.yaml#L29)

```bash
$ conda search docker-py --channel conda-forge
```

```
Loading channels: done
# Name                       Version           Build  Channel
...
docker-py                      3.5.0          py27_0  conda-forge
docker-py                      3.5.0       py27_1000  conda-forge
docker-py                      3.5.0          py35_0  conda-forge
docker-py                      3.5.0          py36_0  conda-forge
docker-py                      3.5.0       py36_1000  conda-forge
docker-py                      3.5.0       py37_1000  conda-forge
...
docker-py                      3.6.0       py27_1000  conda-forge
docker-py                      3.6.0       py36_1000  conda-forge
docker-py                      3.6.0       py37_1000  conda-forge
...
docker-py                      3.7.1          py27_0  conda-forge
docker-py                      3.7.1          py36_0  conda-forge
docker-py                      3.7.1          py37_0  conda-forge
...
language: python
```

Note that this looks a difference between PIP and conda at docker-py side. BTW, it's `docker` at pypi and `docker-py` in conda.

See `https://github.com/conda-forge/docker-py-feedstock/issues/25`
https://github.com/mlflow/mlflow/blob/master/setup.py#L46
https://github.com/conda-forge/mlflow-feedstock/blob/master/recipe/meta.yaml#L29