Compare Series from the same anchor (#1956)
Enable Series.compare to compare Series from the same anchor 

Preivous behavior:
```
>>> kser = ks.Series([1, 2])
>>> kser.compare(kser)
Traceback (most recent call last):
...
AssertionError: We don't need to combine. `this` and `that` are same.

>>> kser.compare(kser + 1)
Traceback (most recent call last):
...
AssertionError: We don't need to combine. `this` and `that` are same.
```

Current behavior:
```
>>> kser = ks.Series([1, 2])
>>> kser.compare(kser)
Empty DataFrame
Columns: [self, other]
Index: []

>>> kser.compare(kser + 1)
   self  other
0     1      2
1     2      3
```