Fix DataFrame.merge to work properly (#2060)
This should resolve #2055 

Before:
```python
>>> kdf = ks.DataFrame(
...     {
...         "lkey": ["foo", "bar", "baz", "foo", "bar", "l"],
...         "rkey": ["baz", "foo", "bar", "baz", "foo", "r"],
...         "value": [1, 1, 3, 5, 6, 7],
...         "x": list("abcdef"),
...         "y": list("efghij"),
...     },
...     columns=["lkey", "rkey", "value", "x", "y"],
... )

>>> left_kdf = kdf[["lkey", "value", "x"]]
>>> right_kdf = kdf[["rkey", "value", "y"]]

>>> ks.merge(left_kdf, right_kdf, on="value")
Traceback (most recent call last):
...
pyspark.sql.utils.AnalysisException: Resolved attribute(s) y#801,rkey#798 missing from lkey#797,y#842,rkey#839,value#799L,__index_level_0__#837L,__natural_order__#808L,__natural_order__#836L,x#800,__index_level_0__#796L,value#840L in operator !Project [lkey#797, value#799L, x#800, rkey#798, y#801]. Attribute(s) with the same name appear in the operation: y,rkey. Please check if the right attribute(s) are used.;;
...
```

After:
```python
>>> kdf = ks.DataFrame(
...     {
...         "lkey": ["foo", "bar", "baz", "foo", "bar", "l"],
...         "rkey": ["baz", "foo", "bar", "baz", "foo", "r"],
...         "value": [1, 1, 3, 5, 6, 7],
...         "x": list("abcdef"),
...         "y": list("efghij"),
...     },
...     columns=["lkey", "rkey", "value", "x", "y"],
... )

>>> left_kdf = kdf[["lkey", "value", "x"]]
>>> right_kdf = kdf[["rkey", "value", "y"]]

>>> ks.merge(left_kdf, right_kdf, on="value")
  lkey  value  x rkey  y
0    l      7  f    r  j
1  bar      6  e  foo  i
2  foo      5  d  baz  h
3  foo      1  a  baz  e
4  foo      1  a  foo  f
5  bar      1  b  baz  e
6  bar      1  b  foo  f
7  baz      3  c  bar  g
```