Add as_index check logic to groupby parameter (#1253)
Resolve https://github.com/databricks/koalas/issues/1252

By doing type validation on item __as_index__  in groupby, 
I think it will be fine if other parameters are added later.
Now, when checking grouping of multiple columns, koalas can find mistakes.

```python
>>> pdf = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
...                   'foo', 'bar', 'foo', 'foo'],
...                    'B': ['one', 'one', 'two', 'three',
...                    'two', 'two', 'one', 'three'],
...                    'C': np.random.randn(8),
...                    'D': np.random.randn(8)})
>>> kdf = ks.from_pandas(pdf)
>>> kdf.groupby('B', 'A').sum().sort_index()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hwpark/Desktop/dev/git_koalas/koalas/databricks/koalas/generic.py", line 1286, in groupby
    'got [%s]' % type(as_index))
TypeError: as_index must be an boolean; however, got [<class 'str'>]
>>> pdf.groupby('B', 'A').sum()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hwpark/Desktop/dev/git_koalas/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 7883, in groupby
    axis = self._get_axis_number(axis)
  File "/Users/hwpark/Desktop/dev/git_koalas/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 411, in _get_axis_number
    raise ValueError("No axis named {0} for object type {1}".format(axis, cls))
ValueError: No axis named A for object type <class 'pandas.core.frame.DataFrame'>
```