Use nullable inferred schema in function apply (#1897)
This PR proposes to use nullable schema in when to apply a function. We take some to infer the schema. Usually types are matched but null or NaN is sparse often. This behaviour is batch with Spark's JSON schema inference as well.

```python
from pyspark.sql import SparkSession
import databricks.koalas as ks
import numpy as np

spark = SparkSession.builder.getOrCreate()
data = list()
for i in range(1, 10000):
  data.append((str(i % 100), np.nan if i % 9999 == 0 else float(i),))

sdf = spark.createDataFrame(data, 'a string, b float').repartition(10)
kdf = sdf.to_koalas()

def f(df):
  return df

df = kdf\
  .groupby('a')\
  .apply(f)

df.to_spark().printSchema()
df[df['b'] == -1]
```

**Before:**

```
root
 |-- a: string (nullable = false)
 |-- b: float (nullable = false)

java.lang.IllegalStateException: Value at index is null
...
```

**After:**

```
root
 |-- a: string (nullable = true)
 |-- b: float (nullable = true)

Empty DataFrame
Columns: [a, b]
Index: []
```

Resolves #1885