Add PyArrow 0.15 support back, and test PyArrow 0.16 in CI (#1110)
This PR adds PyArrow 0.15 support back with a better documentation and error message.
Error message will look as below:

Warning when pyarrow>=0.15 and pyspark<3.0 but `ARROW_PRE_0_15_IPC_FORMAT` not set.

```
WARNING:root:'ARROW_PRE_0_15_IPC_FORMAT' environment variable was not set. It is required 
to set this environment variable to '1' if you use pyarrow>=0.15 and pyspark<3.0. Koalas will 
set it for you but it does not work if there is a Spark context already launched.
```

Exceptions when `ARROW_PRE_0_15_IPC_FORMAT` is set in valid cases:

```
RuntimeError: Please explicitly unset 'ARROW_PRE_0_15_IPC_FORMAT' environment variable 
in both driver and executor sides. Check your spark.executorEnv.*, spark.yarn.appMasterEnv.*, 
spark.mesos.driverEnv.* and spark.kubernetes.driverEnv.* configurations. It is required to set 
this environment variable only when you use pyarrow>=0.15 and pyspark<3.0.
```

```
RuntimeError: Please explicitly unset 'ARROW_PRE_0_15_IPC_FORMAT' environment variable in 
both driver and executor sides. It is required to set this environment variable only when you use 
pyarrow>=0.15 and pyspark<3.0.
```

Resolves #1109