Fix Series.groupby on the Series from different DataFrames. (#1460)
Fixing `Series.groupby` on the Series from different DataFrames.

```py
>>> import databricks.koalas as ks
>>> kdf1 = ks.DataFrame({"C": [0.362, 0.227, 1.267, -0.562], "B": [1, 2, 3, 4]})
>>> kdf2 = ks.DataFrame({"A": [1, 1, 2, 2]})
>>> ks.options.compute.ops_on_diff_frames = True
>>> kdf1.B.groupby(kdf2.A).sum()
Traceback (most recent call last):
...
pyspark.sql.utils.AnalysisException: 'Resolved attribute(s) __tmp_groupkey_0__#118L missing from ...\n'
```