Add DataFrame.pivot (#532)
This PR adds `DataFrame.pivot`.

This is basically same as `pivot_table(aggfunc='first', ...)`.
There are two differences between pandas' `pivot` and `pivot` proposed here to Koalas.

- `values` is required due to support multi index as columns unlike pandas'. This is followup work.

    ```python
    >>> import as pd
    >>> df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
    ...                            'two'],
    ...                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
    ...                     'baz': [1, 2, 3, 4, 5, 6],
    ...                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
    >>> df.pivot(index="foo", columns="bar")
        baz       zoo
    bar   A  B  C   A  B  C
    foo
    one   1  2  3   x  y  z
    two   4  5  6   q  w  t
    >>> df.pivot(index="foo", columns="bar").columns
    MultiIndex(levels=[['baz', 'zoo'], ['A', 'B', 'C']],
               labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]],
               names=[None, 'bar'])
    ```

- pandas' `pivot` raises an value error when duplicated values are found during pivot whereas `pivot` here does not as, up to my knowledge, it is preferred to permissively execute over failing fast when processing large data

    ```python
    >>> import pandas as pd
    >>> df = pd.DataFrame({"foo": ['one', 'one', 'two', 'two'],
    ...                    "bar": ['A', 'A', 'B', 'C'],
    ...                    "baz": [1, 2, 3, 4]}, columns=['foo', 'bar', 'baz'])
    >>> df.pivot(index='foo', columns='bar', values='baz')
    Traceback (most recent call last):
        ...
    ValueError: Index contains duplicate entries, cannot reshape
    ```

Resolves #492