Fix to_list work properly in pandas==0.23 (#1823)
`Koalas` doesn't support `to_list` in `pandas<0.24` because `pandas<0.24` doesn't support `to_list` as an alias for `tolist`.

```python
>>> pd.__version__
'0.23.2'
>>> pser.to_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/haejoon.lee/opt/miniconda3/envs/koalas-dev-3.6/lib/python3.6/site-packages/pandas/core/generic.py", line 4372, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'to_list'
>>> pser.tolist()
[1, 2, 3]
```

This PR fix it to make working `to_list` properly in pandas<0.24.