Adjust data column names before attaching default index. (#1947)
Adjust data column names before attaching default index; otherwise `reset_index()` could fail when the `DataFrame` or `Series` is converted from `Index`.

```py
>>> kdf = ks.Index([10, 20, 30]).to_frame()
>>> kdf
     0
10  10
20  20
30  30
>>> kdf.reset_index()
Traceback (most recent call last):
...
AssertionError: Index columns should not appear in columns of the Spark DataFrame. Avoid index column names [re.compile('__index_level_[0-9]+__')].
```

or

```py
>>> kser = ks.Index([10, 20, 30]).to_series()
>>> kser
10    10
20    20
30    30
dtype: int64
>>> kser.reset_index(drop=True)
Traceback (most recent call last):
...
AssertionError: Index columns should not appear in columns of the Spark DataFrame. Avoid index column names [re.compile('__index_level_[0-9]+__')].
```