Fix groupby when as_index=False. (#1457)
When `as_index=False`, the behavior of groupby for statistic functions like `sum`, `min`, `max`, etc. and `aggregate` function is not the same as pandas'.

```py
>>> pdf = pd.DataFrame({"a": [1, 2, 6, 4, 4, 6, 4, 3, 7], "b": [4, 2, 7, 3, 3, 1, 1, 1, 2]}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9])
>>> pdf.groupby(pdf.b, as_index=False).sum()
   b   a
0  1  13
1  2   9
2  3   8
3  4   1
4  7   6
>>> pdf.groupby(pdf.b + 1, as_index=False).sum()
    a  b
0  13  3
1   9  4
2   8  6
3   1  4
4   6  7
```

For Koalas,

```py
>>> kdf.groupby(kdf.b, as_index=False).sum().sort_values('b')
   b   a
1  1  13
3  2   9
2  3   8
4  4   1
0  7   6
>>> kdf.groupby(kdf.b + 1, as_index=False).sum()
Traceback (most recent call last):
...
ValueError: cannot insert b, already exists
```

The first one is fine, but the second one raises `ValueError` because the key name conflicts the existing column name.

Even if renaming the group key,

```py
>>> pdf.groupby((pdf.b + 1).rename('c'), as_index=False).sum()
    a  b
0  13  3
1   9  4
2   8  6
3   1  4
4   6  7
>>> kdf.groupby((kdf.b + 1).rename('c'), as_index=False).sum()
   c   a  b
0  5   1  4
1  3   9  4
2  8   6  7
3  2  13  3
4  4   8  6
```