Avoid to return a different DataFrame from Series where (and multiple small bug fixes) (#1100)
**1..** We can avoid operations on different DataFrames. See below:

```python
>>> import databricks.koalas as ks
>>> kdf = ks.DataFrame({'a': [1,2,3]})
>>> kdf.a.where(kdf.a > 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../koalas/databricks/koalas/series.py", line 3916, in where
    kdf['__tmp_cond_col__'] = cond
  File "/.../koalas/databricks/koalas/frame.py", line 8089, in __setitem__
    kdf = align_diff_frames(assign_columns, self, value, fillna=False, how="left")
  File "/.../koalas/databricks/koalas/utils.py", line 187, in align_diff_frames
    combined = combine_frames(this, that, how=how)
  File "/.../koalas/databricks/koalas/utils.py", line 122, in combine_frames
    "Cannot combine the series or dataframe because it comes from a different dataframe. "
ValueError: Cannot combine the series or dataframe because it comes from a different dataframe. In order to allow this operation, enable 'compute.ops_on_diff_frames' option.
```

`kdf.a` is from the same DataFrame but currently it requires `compute.ops_on_diff_frames` to be enabled.

This is because `self.to_frame()` creates another DataFrame and it loses it's anchor DataFrame; therefore, it became a different DataFrame.


**2..** We should set `column_index` and `column_index_names`. Otherwise, output DataFrames will lose column indexes (e.g., multi-index columns).

**3..** When we should use `self._kdf` in `Series` API implementation, we should keep check if it matters at output data column because, if we apply some APIs that do not need to create another DataFrame (which is preferred), it will ignore the applied column. See the example below:

```python
ser = df.a.round()  # `kdf` is as is but it only replaces `scol`.
ser._kdf.filter(...).show()  # `scol` is missing in the output
```

**4..** Currently, `compute.ops_on_diff_frames` should only be enabled in `OpsOnDiffFramesEnabledTest`. This option is disabled by default and discouraged due to performance issue.

It was mistakenly enabled at `SeriesTest`. I removed it back.